# Generated by Django 3.1.3 on 2020-11-26 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=20, verbose_name='фамилия')),
                ('first', models.CharField(max_length=20, verbose_name='имя')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='directors/', verbose_name='портрет')),
            ],
            options={
                'ordering': ['last', 'first'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='название')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='год выхода')),
                ('rating', models.FloatField(default=5.0, verbose_name='рейтинг')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='постер')),
                ('plot', models.FileField(blank=True, null=True, upload_to='plots/', verbose_name='сюжет')),
                ('director', models.ForeignKey(blank=True, help_text='режиссер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinopoisk.director')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='комментарий')),
                ('author', models.CharField(max_length=30, verbose_name='автор')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата и время')),
                ('movie', models.ForeignKey(help_text='фильм', on_delete=django.db.models.deletion.CASCADE, to='kinopoisk.movie')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
